# Generated by Django 2.2.7 on 2021-03-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分组ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分组名称')),
                ('sort_no', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name': '分组',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='笔记ID')),
                ('name', models.CharField(max_length=100, verbose_name='笔记名称')),
                ('group_id', models.IntegerField(unique=True, verbose_name='分组ID')),
                ('sort_no', models.IntegerField(verbose_name='排序')),
                ('content', models.TextField(max_length=2048000, verbose_name='笔记内容')),
            ],
            options={
                'verbose_name': '笔记',
            },
        ),
    ]
