# Generated by Django 2.2.7 on 2021-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunnote', '0002_auto_20210322_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sort_no',
            field=models.IntegerField(null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='note',
            name='group_id',
            field=models.IntegerField(null=True, verbose_name='分组ID'),
        ),
    ]
